# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CulvertDesigner
                                 A QGIS plugin
 This plugin adds an algorithm to automate rural drainage assessment,  integrating catchment delineation,  flow estimation,  and culvert sizing with cost optimization for preliminary design workflows.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-21
        copyright            : (C) 2025 by Blake Hillwood
        email                : blakeh1998@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Blake Hillwood'
__date__ = '2025-07-21'
__copyright__ = '(C) 2025 by Blake Hillwood'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CulvertDesigner class from file CulvertDesigner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis_culvert_designer import CulvertDesignerPlugin
    return CulvertDesignerPlugin()
