# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CulvertDesigner
                                 A QGIS plugin
 This plugin adds an algorithm to automate rural drainage assessment,  integrating catchment delineation,  flow estimation,  and culvert sizing with cost optimization for preliminary design workflows.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-21
        copyright            : (C) 2025 by Blake Hillwood
        email                : blakeh1998@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Blake Hillwood'
__date__ = '2025-07-21'
__copyright__ = '(C) 2025 by Blake Hillwood'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsApplication
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon
import processing

from .qgis_culvert_designer_provider import CulvertDesignerProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class CulvertDesignerPlugin(object):

    def __init__(self, iface):
        self.provider = None
        self.iface = iface
        self.actions = []

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = CulvertDesignerProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

        def add_btn(text, alg_id, icon = 'icon.jpg', if_toolbar_icon=False):
            action = QAction(
                QIcon(os.path.join(cmd_folder, icon)),
                text, self.iface.mainWindow())
            action.triggered.connect(lambda: processing.execAlgorithmDialog(alg_id))
            self.iface.addPluginToMenu(u"Culvert Designer", action)
            if if_toolbar_icon:
                self.iface.addToolBarIcon(action)
            self.actions.append(action)


        add_btn("Step 1: Hydrology", "CulvertDesign:step1_hydro")
        add_btn("Step 2: Culvert network extraction", "CulvertDesign:step2_culvert_network")
        add_btn("Step 3: Flow‑rate calculation", "CulvertDesign:step3_flowrates")
        add_btn("Step 4: Culvert sizing & 1d_nwk update", "CulvertDesign:step4_sizeculverts")
        add_btn("Run full Culvert Designer workflow", "CulvertDesign:culvert_designer", if_toolbar_icon=True)
     
     

    def unload(self):
        if self.provider:
             QgsApplication.processingRegistry().removeProvider(self.provider)
        for action in self.actions:
            self.iface.removePluginMenu(u"Culvert Designer", action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        processing.execAlgorithmDialog("CulvertDesign:culvert_designer")
